/* Write your T-SQL query statement below */

SELECT U.NAME, SUM(T.AMOUNT) AS [BALANCE]
FROM USERS AS U
INNER JOIN
TRANSACTIONS AS T
ON
U.ACCOUNT = T.ACCOUNT
GROUP BY U.NAME
HAVING SUM(T.AMOUNT) > 10000

